export const syllabus = [
  {
    id: 'engineering-mathematics',
    name: 'Engineering Mathematics',
    topics: [
      { id: 'em-discrete-propositional-first-order-logic', name: 'Propositional and first order logic' },
      { id: 'em-discrete-sets', name: 'Sets' },
      { id: 'em-discrete-relations', name: 'relations' },
      { id: 'em-discrete-functions', name: 'functions' },
      { id: 'em-discrete-partial-orders-lattices', name: 'partial orders and lattices' },
      { id: 'em-discrete-monoids', name: 'monoids' },
      { id: 'em-discrete-groups', name: 'groups' },
      { id: 'em-discrete-graphs-connectivity-matching-colouring', name: 'graphs connectivity, matching, colouring' },
      { id: 'em-discrete-combinatorics-counting', name: 'combinatorics counting' },
      { id: 'em-discrete-recurrence-relations', name: 'recurrence relations' },
      { id: 'em-discrete-generating-functions', name: 'generating functions' },
      { id: 'em-linear-algebra-matrices', name: 'matrices' },
      { id: 'em-linear-algebra-determinants', name: 'determinants' },
      { id: 'em-linear-algebra-system-of-linear-equations', name: 'system of linear equations' },
      { id: 'em-linear-algebra-eigenvalues-eigenvectors', name: 'eigenvalues and eigenvectors' },
      { id: 'em-linear-algebra-lu-decomposition', name: 'LU decomposition' },
      { id: 'em-calculus-limits', name: 'limits' },
      { id: 'em-calculus-continuity-differentiability', name: 'continuity and differentiability' },
      { id: 'em-calculus-maxima-minima', name: 'maxima and minima' },
      { id: 'em-calculus-mean-value-theorem', name: 'mean value theorem' },
      { id: 'em-calculus-integration', name: 'integration' },
      { id: 'em-probability-random-variables', name: 'random variables' },
      { id: 'em-probability-distributions', name: 'uniform, normal, exponential, Poisson, binomial distributions' },
      { id: 'em-probability-measures', name: 'mean, median, mode, standard deviation' },
      { id: 'em-probability-conditional-probability', name: 'conditional probability' },
      { id: 'em-probability-bayes-theorem', name: 'Bayes theorem' },
    ],
  },
  {
    id: 'digital-logic',
    name: 'Digital Logic',
    topics: [
      { id: 'dl-boolean-algebra', name: 'Boolean algebra' },
      { id: 'dl-minimization-algebraic-technique', name: 'minimization: algebraic technique' },
      { id: 'dl-minimization-karnaugh-map', name: 'minimization: Karnaugh map' },
      { id: 'dl-minimization-tabular-method', name: 'minimization: tabular method' },
      { id: 'dl-design-combinational-circuits', name: 'design of combinational circuits' },
      { id: 'dl-design-sequential-circuits', name: 'design of sequential circuits' },
      { id: 'dl-number-representation', name: 'number representation' },
      { id: 'dl-arithmetic-fixed-point', name: 'arithmetic fixed point' },
      { id: 'dl-arithmetic-floating-point', name: 'arithmetic floating point' },
    ],
  },
  {
    id: 'computer-organization-and-architecture',
    name: 'Computer Organization and Architecture',
    topics: [
      { id: 'coa-instruction-set', name: 'instruction set' },
      { id: 'coa-addressing-modes', name: 'addressing modes' },
      { id: 'coa-alu', name: 'ALU' },
      { id: 'coa-control-unit', name: 'control unit hardwired/microprogrammed' },
      { id: 'coa-memory-interfacing-hierarchy', name: 'memory interfacing and hierarchy' },
      { id: 'coa-performance', name: 'performance' },
      { id: 'coa-cache-memory', name: 'cache memory' },
      { id: 'coa-cache-mapping', name: 'cache mapping' },
      { id: 'coa-io-interface', name: 'I/O interface' },
      { id: 'coa-interrupt', name: 'interrupt' },
      { id: 'coa-dma', name: 'DMA' },
      { id: 'coa-instruction-pipelining', name: 'instruction pipelining' },
      { id: 'coa-pipeline-hazards', name: 'pipeline hazards' },
    ],
  },
  {
    id: 'programming-and-data-structures',
    name: 'Programming and Data Structures',
    topics: [
      { id: 'pds-c', name: 'C' },
      { id: 'pds-recursion', name: 'recursion' },
      { id: 'pds-arrays', name: 'arrays' },
      { id: 'pds-stacks', name: 'stacks' },
      { id: 'pds-queues', name: 'queues' },
      { id: 'pds-linked-lists', name: 'linked lists' },
      { id: 'pds-trees', name: 'trees' },
      { id: 'pds-binary-search-trees', name: 'binary search trees' },
      { id: 'pds-binary-heaps', name: 'binary heaps' },
      { id: 'pds-graphs', name: 'graphs' },
    ],
  },
  {
    id: 'algorithms',
    name: 'Algorithms',
    topics: [
      { id: 'alg-searching', name: 'searching' },
      { id: 'alg-sorting', name: 'sorting' },
      { id: 'alg-hashing', name: 'hashing' },
      { id: 'alg-asymptotic-worst-case-time-complexity', name: 'asymptotic worst-case time complexity' },
      { id: 'alg-asymptotic-worst-case-space-complexity', name: 'asymptotic worst-case space complexity' },
      { id: 'alg-greedy', name: 'greedy' },
      { id: 'alg-dynamic-programming', name: 'dynamic programming' },
      { id: 'alg-divide-and-conquer', name: 'divide-and-conquer' },
      { id: 'alg-graph-traversals', name: 'graph traversals' },
      { id: 'alg-mst', name: 'MST' },
      { id: 'alg-shortest-paths', name: 'shortest paths' },
    ],
  },
  {
    id: 'theory-of-computation',
    name: 'Theory of Computation',
    topics: [
      { id: 'toc-regular-expressions', name: 'regular expressions' },
      { id: 'toc-finite-automata', name: 'finite automata' },
      { id: 'toc-cfg', name: 'CFG' },
      { id: 'toc-pda', name: 'PDA' },
      { id: 'toc-regular-languages', name: 'regular languages' },
      { id: 'toc-cfl', name: 'CFL' },
      { id: 'toc-pumping-lemma', name: 'pumping lemma' },
      { id: 'toc-turing-machines', name: 'Turing machines' },
      { id: 'toc-undecidability', name: 'undecidability' },
    ],
  },
  {
    id: 'compiler-design',
    name: 'Compiler Design',
    topics: [
      { id: 'cd-lexical-analysis', name: 'lexical analysis' },
      { id: 'cd-parsing', name: 'parsing' },
      { id: 'cd-syntax-directed-translation', name: 'syntax-directed translation' },
      { id: 'cd-runtime-environments', name: 'runtime environments' },
      { id: 'cd-intermediate-code-generation', name: 'intermediate code generation' },
      { id: 'cd-local-optimisation', name: 'local optimisation' },
      { id: 'cd-data-flow-analyses', name: 'data flow analyses' },
      { id: 'cd-constant-propagation', name: 'constant propagation' },
      { id: 'cd-liveness-analysis', name: 'liveness analysis' },
      { id: 'cd-common-subexpression-elimination', name: 'common subexpression elimination' },
    ],
  },
  {
    id: 'operating-system',
    name: 'Operating System',
    topics: [
      { id: 'os-system-calls', name: 'system calls' },
      { id: 'os-processes', name: 'processes' },
      { id: 'os-threads', name: 'threads' },
      { id: 'os-ipc', name: 'IPC' },
      { id: 'os-concurrency', name: 'concurrency' },
      { id: 'os-synchronization', name: 'synchronization' },
      { id: 'os-deadlock', name: 'deadlock' },
      { id: 'os-cpu-scheduling', name: 'CPU scheduling' },
      { id: 'os-io-scheduling', name: 'I/O scheduling' },
      { id: 'os-memory-management', name: 'memory management' },
      { id: 'os-virtual-memory', name: 'virtual memory' },
      { id: 'os-file-systems', name: 'file systems' },
    ],
  },
  {
    id: 'databases',
    name: 'Databases',
    topics: [
      { id: 'db-er-model', name: 'ER model' },
      { id: 'db-relational-model', name: 'relational model' },
      { id: 'db-relational-algebra', name: 'relational algebra' },
      { id: 'db-tuple-calculus', name: 'tuple calculus' },
      { id: 'db-sql', name: 'SQL' },
      { id: 'db-integrity-constraints', name: 'integrity constraints' },
      { id: 'db-normal-forms', name: 'normal forms' },
      { id: 'db-file-organization', name: 'file organization' },
      { id: 'db-indexing', name: 'indexing' },
      { id: 'db-b-plus-tree', name: 'B+ tree' },
      { id: 'db-transactions', name: 'transactions' },
      { id: 'db-concurrency-control', name: 'concurrency control' },
    ],
  },
  {
    id: 'computer-networks',
    name: 'Computer Networks',
    topics: [
      { id: 'cn-principles-of-layering', name: 'principles of layering' },
      { id: 'cn-basics-of-switching', name: 'basics of switching' },
      { id: 'cn-circuit-switching', name: 'circuit switching' },
      { id: 'cn-packet-switching', name: 'packet switching' },
      { id: 'cn-virtual-circuit', name: 'virtual circuit' },
      { id: 'cn-performance-metrics', name: 'performance metrics' },
      { id: 'cn-data-link-layer', name: 'data link layer' },
      { id: 'cn-error-detection', name: 'error detection' },
      { id: 'cn-mac', name: 'MAC' },
      { id: 'cn-ethernet', name: 'Ethernet' },
      { id: 'cn-distance-vector', name: 'distance vector' },
      { id: 'cn-link-state', name: 'link state' },
      { id: 'cn-ipv4', name: 'IPv4' },
      { id: 'cn-fragmentation', name: 'fragmentation' },
      { id: 'cn-cidr', name: 'CIDR' },
      { id: 'cn-nat', name: 'NAT' },
      { id: 'cn-tcp', name: 'TCP' },
      { id: 'cn-flow-control', name: 'flow control' },
      { id: 'cn-congestion-control', name: 'congestion control' },
      { id: 'cn-socket-api', name: 'socket API' },
      { id: 'cn-dns', name: 'DNS' },
      { id: 'cn-http', name: 'HTTP' },
    ],
  },
];

export const totalTopicCount = syllabus.reduce((total, section) => total + section.topics.length, 0);

export function getSectionProgress(section, completedTopicIds) {
  const completedCount = section.topics.reduce(
    (count, topic) => count + Number(completedTopicIds.has(topic.id)),
    0
  );
  return {
    completedCount,
    totalCount: section.topics.length,
    percentage: section.topics.length === 0 ? 0 : (completedCount / section.topics.length) * 100,
  };
}

export function getOverallProgress(completedTopicIds) {
  const completedCount = syllabus.reduce(
    (total, section) =>
      total + section.topics.reduce((count, topic) => count + Number(completedTopicIds.has(topic.id)), 0),
    0
  );
  return {
    completedCount,
    totalCount: totalTopicCount,
    percentage: totalTopicCount === 0 ? 0 : (completedCount / totalTopicCount) * 100,
  };
}
